[tool.poetry]
name = "cardano-autonomous-agent"
version = "0.1.0"
description = ""
authors = ["sital999 <sitalnagarkoti123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
