version: '3.8'
services:
  api:
    image: cardanoapi/autonomous-agents-api:${IMAGE_TAG}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/autonomous_agents_preprod
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_PREFIX=aat-preprod
      - DOCS_URL=/api/docs
      - OPENAPI_URL=/api/openapi.json
      - VIRTUAL_HOST=https://preprod.api.agents.cardanoapi.io
      - KAFKA_ENABLED=true
      - AGENT_MNEMONIC=${AGENT_MNEMONIC}
      - KUBER_URL=https://preprod.kuber.cardanoapi.io/api/v3
      - KUBER_API_KEY=${KUBER_API_KEY}
      - DB_SYNC_BASE_URL=http://dbsync-preprod:8080/api
      - ELASTIC_APM_API_KEY=${ELASTIC_APM_API_KEY}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL}
      - ELASTIC_APM_ENVIRONMENT=preprod
      - METADATA_BASE_URL=https://metadata.drep.id/api

      
    networks:
      - default
      - postgres
      - frontend
      - kafka
      - dbsync-api

    deploy:
      restart_policy:
        delay: 10s
      update_config:
        order: start-first
      placement:
        constraints:
         -  node.labels.caat==true
         
  agent-manager:
    image: cardanoapi/autonomous-agents-agent-manager:${IMAGE_TAG}
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/autonomous_agents_preprod
      - KAFKA_BROKERS=172.31.0.5:29092
      - KAFKA_PREFIX=aat-preprod
      - CARDANO_NODE_URL=172.31.0.3:3002
      - CARDANO_NETWORK_MAGIC=1
      - API_SERVER=http://api:8000
      - VIRTUAL_HOST=https+wss://preprod.manager.agents.cardanoapi.io->:3001
      - KUBER_BASE_URL=https://preprod.kuber.cardanoapi.io
      - KUBER_API_KEY=${KUBER_API_KEY}
      - MANAGER_WALLET_ADDRESS=${MANAGER_WALLET_ADDRESS}
      - MANAGER_WALLET_SIGNING_KEY=${MANAGER_WALLET_SIGNING_KEY}
      - AGENT_MNEMONIC=${AGENT_MNEMONIC}
      - DB_SYNC_BASE_URL=http://dbsync-preprod:8080/api
      - ELASTIC_APM_API_KEY=${ELASTIC_APM_API_KEY}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL}
      - ELASTIC_APM_ENVIRONMENT=preprod
      - ENABLE_BLOCKFROST_SUBMIT_API=true
      - BLOCKFROST_API_KEY=${BLOCKFROST_API_KEY}
      - METADATA_BASE_URL=https://metadata.drep.id/api
      - NETWORK_NAME=preprod

    networks:
      - default
      - postgres
      - kafka
      - frontend
      - dbsync-api

    deploy:
      restart_policy:
        delay: 10s
      update_config:
        order: start-first
      placement:
        constraints:
         -  node.labels.caat==true

networks:
  frontend:
    external: true
    name: frontend2
  kafka:
    external: true
  postgres:
    external: true
  dbsync-api:
    external: true

