import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';

import { Provider } from 'jotai';
// import '@uiw/react-markdown-preview/dist/markdown.min.css';
// import '@uiw/react-markdown-preview/esm/styles/markdown.css';
// import '@uiw/react-md-editor/dist/mdeditor.min.css';
// import 'katex/dist/katex.min.css';
// import 'react-phone-input-2/lib/style.css';
import 'nprogress/nprogress.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'vanilla-cookieconsent/dist/cookieconsent.css';

import '@app/assets/css/globals.css';
import '@app/assets/css/tailwind.css';
import SideNav, { ISideNavItem } from '@app/components/layout/SideNav';
import TopNav from '@app/components/layout/TopNav';
import ThemeProvider from '@app/shared/hocs/ThemeProvider';
import CookieConsent from '@app/views/atoms/CookieConsent';
import NextNProgress from '@app/views/atoms/NextNProgress';
import {QueryClient , QueryClientProvider} from '@tanstack/react-query'
import { lazy } from 'react';
import ReactQueryProvider from '@app/utils/providers/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] });
const queryClient = new QueryClient()

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '400', '500', '600', '700', '800'],
    display: "swap"
});

export const metadata: Metadata = {
    title: 'Cardano Autonomous Agent',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className=''>
            <body className={poppins.className}>
                <ThemeProvider>
                    <CookieConsent />
                    <NextNProgress
                        color="#0764EB"
                        startPosition={0}
                        stopDelayMs={400}
                        height={2}
                        options={{ easing: 'ease' }}
                    />
                    <ToastContainer
                        position="bottom-center"
                        autoClose={5000}
                        hideProgressBar
                        newestOnTop
                        closeOnClick
                        rtl={false}
                        pauseOnFocusLoss={false}
                        draggable
                        pauseOnHover={false}
                        theme="dark"
                    />
                    <Provider>
                        <ReactQueryProvider>
                        <div className="flex h-full w-full ">
                            <div className="h-screen w-[20%] ">
                                <SideNav />
                            </div>
                            <div className="mx-[2%] mt-[3%] min-h-full flex-col w-[80%] overflow-y-auto no-scrollbar">
                                <TopNav />
                                <div className="mt-12 h-full">{children}</div>
                            </div>
                        </div>
                        </ReactQueryProvider>
                    </Provider>
                </ThemeProvider>
            </body>
        </html>
    );
}
