name: Black Lint

on:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches:
            - master
            - dev
        paths:
            - 'api/**'
            - .github/workflows/black-lint.yml
jobs:
    black-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: psf/black@stable
              with:
                  src: "./api"
